version: '{build}'
branches:
  only:
  - master
image: Visual Studio 2017
configuration: Release
environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
cache:
- src\packages -> **\packages.config
- '%LocalAppData%\NuGet\Cache'
- '%LocalAppData%\NuGet\v3-cache'
nuget:
  disable_publish_on_pr: true
build_script:
- ps: .\build-utils\Build.ps1
test_script:
- cmd: dotnet test "tests\Couchbase.Extensions.DependencyInjection.UnitTests"
- cmd: dotnet test "tests\Couchbase.Extensions.DnsDiscovery.UnitTests"
- cmd: dotnet test "tests\Couchbase.Extensions.Caching.UnitTests"
artifacts:
- path: '*.nupkg'
deploy:
- provider: NuGet
  api_key:
    secure: KzT1ESVyB5LB0Ovg+dPUmvZYQJ0XYoBEe9DW1pBDKzv0y/7y2RlJ1xt16ZI5dnVE
  artifact: DependencyInjection
  on:
    APPVEYOR_REPO_TAG: true
- provider: NuGet
  api_key:
    secure: KzT1ESVyB5LB0Ovg+dPUmvZYQJ0XYoBEe9DW1pBDKzv0y/7y2RlJ1xt16ZI5dnVE
  artifact: DnsDiscovery
  on:
    APPVEYOR_REPO_TAG: true
notifications:
- provider: GitHubPullRequest
  auth_token:
    secure: ULHzhdaGoUWJwQqameGnvmg+61OInc0YMit2rTezp2pi3ZB4ehCq4T0h3WbnVEcu
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
